---
name: Publish

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: GitHub Releases
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build
        uses: xu-cheng/latex-action@v2
        with:
          root_file: tex/makenew-latex-project.tex
          work_in_root_file_dir: true
          latexmk_use_xelatex: true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          files: tex/*.pdf
